Pseez.VisitRegistration/Controllers/IdentityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using Identity.ServiceLayer.Interfaces;
using Microsoft.AspNet.Identity;
using Identity.ViewModels.ViewModels;
using Identity.Models.Models;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Pseez.VisitRegistration.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IdentityController : Controller
    {
        private IIdentityUserService _identityUserService;
        private IIdentityRoleService _identityRoleService;
        private IIdentityUserRoleService _identityUserRoleService;
        //private Task<IdentityResult> _createUserAsync;

        public IdentityController(IIdentityUserService identityUserService,
            IIdentityRoleService identityRoleService,
            IIdentityUserRoleService identityUserRoleService)
        {
            _identityUserService = identityUserService;
            _identityRoleService = identityRoleService;
            _identityUserRoleService = identityUserRoleService;
        }

        //
        // GET: /Admin/Admin/
        public ActionResult Index()
        {
            return View();
        }



        #region Users
        //===========================================================================================
        //                Users
        //===========================================================================================
        public ActionResult AllUsers()
        {
            return View(_identityUserService.GetAllUsers().OrderBy(r => r.UserName));
        }

        public ActionResult AllUsersRead()
        {
            IEnumerable<ApplicationUser> a = _identityUserService.GetAllUsers().ToList();
            return Json(a, JsonRequestBehavior.AllowGet);
        }

        // GET: /Admin/CreateUser
        public ActionResult CreateUser()
        {
            return PartialView("_CreateUser");
        }

        // POST: /Admin/CreateUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateUser(RegisterViewModelwithName registerViewModelwithName)
        {
            if (ModelState.IsValid)
            {
                var result = await _identityUserService.CreateUserAsync(userName: registerViewModelwithName.UserName, email: registerViewModelwithName.Email, password: registerViewModelwithName.Password);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    AddErrors(result);
                }
            }
            return PartialView("_CreateUser", registerViewModelwithName);
        }

        // GET: /Admin/EditUser/5
        public async Task<ActionResult> EditUser(string id = null)
        {
            ApplicationUser user = await _identityUserService.FindUserById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return PartialView("_EditUser", user);
        }

        // POST: /Admin/EditUser/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditUser(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                var result = await _identityUserService.UpdateUserAsync(user);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    AddErrors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "Uncorrect Input.");
            }
            return PartialView("_EditUser", user);
        }

        // GET: /Admin/DeleteUser/5
        public async Task<ActionResult> DeleteUser(string id = null)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            ApplicationUser user = await _identityUserService.FindUserById(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            else
            {
                return PartialView("_DeleteUser", user);
            }
        }
        // POST: /Admin/DeleteUser/5
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteUserConfirmed(string id = null)
        {
            try
            {
                var result = await _identityUserService.DeleteUserByIdAsync(id);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    AddErrors(result);
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            ApplicationUser user = await _identityUserService.FindUserById(id);
            return PartialView("_DeleteUser", user);
        }
        #endregion




        #region Roles
        //===========================================================================================
        //                Roles
        //===========================================================================================
        public ActionResult AllRoles()
        {
            //IEnumerable<IdentityRole> allRoles = _identityRoleService.GetAllRoles().OrderBy(r => r.Name);
            //return View("AllRoles", allRoles);
            return View();
        }

        public ActionResult AllRolesRead()
        {
            //IEnumerable<IdentityRole> a = _identityRoleService.GetAllRoles();
            var a = _identityRoleService.GetAllRoles().ToList();
            return Json(a, JsonRequestBehavior.AllowGet);
        }

        // GET: /Admin/CreateRole
        public ActionResult CreateRole()
        {
            return PartialView("_CreateRole");
        }

        // POST: /Admin/CreateRole
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateRole(string roleName)
        {
            if (ModelState.IsValid)
            {
                var result = await _identityRoleService.CreateRoleByNameAsync(roleName);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    AddErrors(result);
                }
            }
            return PartialView("_CreateRole", roleName);
        }

        // GET: /Admin/EditRole/5
        public async Task<ActionResult> EditRole(string id = null)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            IdentityRole identityRole = await _identityRoleService.FindRoleByIdAsync(id);
            return PartialView("_EditRole", identityRole);
        }

        // POST: /Admin/EditRole/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditRole(string id, string name)
        {
            IdentityRole identityRole = await _identityRoleService.FindRoleByIdAsync(id);
            identityRole.Name = name;
            if (ModelState.IsValid)
            {
                var result = await _identityRoleService.UpdateRoleAsync(identityRole);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    AddErrors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "Uncorrect Input.");
            }
            return PartialView("_EditRole", identityRole);
        }

        // GET: /Admin/DeleteRole/5
        public async Task<ActionResult> DeleteRole(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            else
            {
                IdentityRole role = await _identityRoleService.FindRoleByIdAsync(id);
                return PartialView("_DeleteRole", role);
            }
        }
        // POST: /Admin/DeleteRole/5
        [HttpPost, ActionName("DeleteRole")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteRoleConfirmed(string id)
        {
            try
            {
                var result = await _identityRoleService.DeleteRoleByIdAsync(id);
                if (result.Succeeded)
                {
                    return Json(new { success = true });
                }
                else
                {
                    AddErrors(result);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            IdentityRole role = await _identityRoleService.FindRoleByIdAsync(id);
            return PartialView("_DeleteRole", role);
        }
        #endregion Roles




        #region Users in Roles
        //===========================================================================================
        //                Users Roles
        //===========================================================================================
        public ActionResult AllUsersRoles()
        {
            IEnumerable<UserRoleViewModel> userRoles = _identityUserRoleService.GetAllUsersRoles().OrderBy(r => r.UserName);
            return View(userRoles);
        }

        public ActionResult AllUsersRolesRead()
        {
            IEnumerable<UserRoleViewModel> userRoleViewModel = _identityUserRoleService.GetAllUsersRoles().OrderBy(r => r.UserName).ToList();
            return Json(userRoleViewModel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddUserRole()
        {

Pseez.VisitRegistration/Views/Identity - Copy/AllRoles.cshtml
@using Microsoft.AspNet.Identity.EntityFramework;
@model IEnumerable<IdentityRole>

@{
    ViewBag.Title = "All Roles";
}

<h2>All Roles</h2>

<p>
    @Html.ActionLink("New Role", "CreateRole", null, new { @class = "btn btn-primary", data_modal = "" })
</p>

<div class="row">
    <div class="col-md-4">
        <table class="table table-striped table-bordered table-hover table-responsive">
            <tr>
                @*<th>
                        کد گروه
                    </th>*@
                <th>
                    Role Name
                </th>
                <th style="width:110px"></th>
            </tr>

            @foreach (IdentityRole Role1 in Model)
            {
                <tr>
                    @*<td>
                            @Html.DisplayFor(modelItem => Role1.Id)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => Role1.Name)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "EditRole", new { id = Role1.Id }, new { @class = "btn btn-info glyphicon glyphicon-edit", data_modal = "" })
                        @Html.ActionLink(" ", "DeleteRole", new { id = Role1.Id }, new { @class = "btn btn-danger glyphicon glyphicon-trash", data_modal = "" })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
@*--------------------------------------------
    ---------------- Modal  ---------------------
    --------------------------------------------*@

<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(function () {
            $.ajaxSetup({ cache: false });
            $("a[data-modal]").on("click", function (e) {
                $('#myModalContent').load(this.href, function () {
                    $('#myModal').modal({
                        keyboard: true
                    }, 'show');
                    bindForm(this);
                });
                return false;
            });
        });

        function bindForm(dialog) {
            $('form', dialog).submit(function () {
                $('#progress').show();
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            $('#myModal').modal('hide');
                            $('#progress').hide();
                            location.reload();
                        } else {
                            $('#progress').hide();
                            $('#myModalContent').html(result);
                            bindForm();
                        }
                    }
                });
                return false;
            });
        }
    </script>
}

Pseez.VisitRegistration/Views/Identity - Copy/AllUsers.cshtml
@model IEnumerable<Identity.Models.Models.ApplicationUser>

@{
    ViewBag.Title = "Users";
}

<h2>Users</h2>

<p>
    @Html.ActionLink("New User", "CreateUser", null, new { @class = "btn btn-primary", data_modal = "" })
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-bordered table-hover table-responsive table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th style="width:110px"></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>

                        @Html.ActionLink(" ", "EditUser", new { id = item.Id }, new { @class = "btn btn-info glyphicon glyphicon-edit", data_modal = "" })
                        @Html.ActionLink(" ", "DeleteUser", new { id = item.Id }, new { @class = "btn btn-danger glyphicon glyphicon-trash", data_modal = "" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

@*--------------------------------------------
    ---------------- Modal  ---------------------
    --------------------------------------------*@

<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>


@section Styles{

@section Scripts{

    <script>
        //نمایش مودال
        function ShowModal(Address) {
            $('#myModalContent').load(Address, function () {
                $('#myModal').modal({
                    keyboard: true
                }, 'show');
                bindForm(this);
            });
            return false;
        };
        function bindForm(dialog) {
            $('form', dialog).submit(function () {
                $('#progress').show();
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            $('#myModal').modal('hide');
                            $('#progress').hide();
                            location.reload();
                        } else {
                            $('#progress').hide();
                            $('#myModalContent').html(result);
                            bindForm();
                        }
                    }
                });
                return false;
            });
        };
    </script>
}

Pseez.VisitRegistration/Views/Identity - Copy/AllUsersInRoles.cshtml
@*@using Microsoft.AspNet.Identity.EntityFramework;
    @model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityUserRole>*@

@using Identity.ViewModels.ViewModels;
@model IEnumerable<Identity.ViewModels.ViewModels.UserRoleViewModel>

@{
    ViewBag.Title = "Manage Roles";
}

<h2>Users in Roles</h2>

<p>
    @Html.ActionLink("Add user to role", "AddUserInRole", null, new { @class = "btn btn-primary", data_modal = "" })
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-bordered table-hover table-responsive table-striped">
            <tr>
                <th>
                    Role
                </th>
                <th>
                    User
                </th>
                <th style="width:110px"></th>
            </tr>

            @foreach (UserRoleViewModel IdentityUserRole1 in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => IdentityUserRole1.RoleName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => IdentityUserRole1.UserName)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "DeleteUserInRole", new { UserName = IdentityUserRole1.UserName, RoleName = IdentityUserRole1.RoleName }, new { @class = "btn btn-danger glyphicon glyphicon-trash", data_modal = "" })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

@*--------------------------------------------
    ---------------- Modal  ---------------------
    --------------------------------------------*@

<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(function () {
            $.ajaxSetup({ cache: false });
            $("a[data-modal]").on("click", function (e) {
                $('#myModalContent').load(this.href, function () {
                    $('#myModal').modal({
                        keyboard: true
                    }, 'show');
                    bindForm(this);
                });
                return false;
            });
        });

        function bindForm(dialog) {
            $('form', dialog).submit(function () {
                $('#progress').show();
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        if (result.success) {
                            $('#myModal').modal('hide');
                            $('#progress').hide();
                            location.reload();
                        } else {
                            $('#progress').hide();
                            $('#myModalContent').html(result);
                            bindForm();
                        }
                    }
                });
                return false;
            });
        }
    </script>
}

Pseez.VisitRegistration/Views/Identity - Copy/Index.cshtml
@{
    ViewBag.Title = "Manage Users";
}

<h2>Manage Users</h2>

<section class="row">
    <div class="col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading text-center">
                <h3>Manage Users</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>@Html.ActionLink("Users", "AllUsers", "Identity")</li>
                    <li>@Html.ActionLink("Roles", "AllRoles", "Identity")</li>
                    <li>@Html.ActionLink("Users In Roles", "AllUsersInRoles", "Identity")</li>
                </ul>
            </div>
        </div>
    </div>
</section>

Pseez.VisitRegistration/Views/Identity - Copy/_AddUserInRole.cshtml
@*@model Portal.Models.UserProfile*@


<div class="modal-header alert-info">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">Add User to Role</h3>
</div>


@using (Html.BeginForm("AddUserInRole", "Identity", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="modal-body">
        <div class="form-group">
            <label class="control-label col-md-2" for="User1">User</label>
            <div class="col-md-10">
                @Html.DropDownList("User1", new SelectList(ViewBag.UserNames), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="Role1">Role</label>
            <div class="col-md-10">
                @Html.DropDownList("Role1", new SelectList(ViewBag.RoleNames), new { @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Meh/Images/wait.gif" alt="wait" />
            Sending ...
        </span>

        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>
}

Pseez.VisitRegistration/Views/Identity - Copy/_CreateRole.cshtml
@{
    ViewBag.Title = "Create Role";
}


<div class="modal-header alert-info">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">@ViewBag.Title</h3>
</div>

@using (Html.BeginForm())
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.Label("RoleName", "Role Name", new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextBox("RoleName", null, new { @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Meh/Images/wait.gif" alt="wait" />
            Sending ...
        </span>

        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>
}

Pseez.VisitRegistration/Views/Identity - Copy/_CreateUser.cshtml
@model Identity.ViewModels.ViewModels.RegisterViewModelwithName

@{
    ViewBag.Title = "Create User";
}

<div class="modal-header alert-info">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">@ViewBag.Title</h3>
</div>

@using (Html.BeginForm())
{
    <div class="modal-body">

        <div class="form-horizontal">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @*<fieldset>
                <legend>ساخت حساب کاربری</legend>*@
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", dir = "ltr" })
                    @Html.ValidationMessageFor(model => model.UserName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", dir = "ltr" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control", dir = "ltr" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", dir = "ltr", type = "email" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>
        </div>
    </div>


    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Meh/Images/wait.gif" alt="wait" />
            Sending ...
        </span>

        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>
}

@*<div>
        @Html.ActionLink("بازگشت به لیست", "AllUsers")
    </div>*@

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

Pseez.VisitRegistration/Views/Identity - Copy/_DeleteRole.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Delete Role";
}

<div class="modal-header alert-danger">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">@ViewBag.Title</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(m => Model.Name, new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control required", @disabled = "disabled" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-9 col-sm-offset-3">
                    <h3>
                        <span class="label label-danger">
                            Are you sure?
                        </span>
                    </h3>
                </div>
            </div>
        </div>
    </div>


    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Yes" />
        <button class="btn btn-primary" data-dismiss="modal">No</button>
    </div>
}

Pseez.VisitRegistration/Views/Identity - Copy/_DeleteUser.cshtml
@*@model Microsoft.AspNet.Identity.EntityFramework.IdentityUser*@
@model Identity.Models.Models.ApplicationUser
@{
    ViewBag.Title = "Delete User";
}

<div class="modal-header alert-danger">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">Delete User</h3>
</div>


<div class="modal-body">
    <div class="form-horizontal">

        <div class="form-group">
            @Html.Label("UserName", "User Name", new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", dir = "ltr", @disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", dir = "ltr", @disabled = "disabled" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <h3>
                    <span class="label label-danger">
                        Are you sure?
                    </span>
                </h3>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Yes" />
        <button class="btn btn-primary" data-dismiss="modal">No</button>
    </div>
}

Pseez.VisitRegistration/Views/Identity - Copy/_DeleteUserInRole.cshtml
<div class="modal-header alert-danger">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">Delete user from role</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                @Html.Label("UserName", "User Name", new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.TextBox("UserName", (string)ViewBag.UserName1, new { @class = "form-control required", @disabled = "disabled" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("RoleName", "Group Name", new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.TextBox("RoleName", (string)ViewBag.RoleName1, new { @class = "form-control required", @disabled = "disabled" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-9 col-sm-offset-3">
                    <h3>
                        <span class="label label-danger">
                            Are you sure?
                        </span>
                    </h3>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Yes" />
        <button class="btn btn-primary" data-dismiss="modal">No</button>
    </div>
}

Pseez.VisitRegistration/Views/Identity - Copy/_EditRole.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

<div class="modal-header alert-info">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span></button>
    <h3 class="modal-title">Edit Role</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div class="modal-body">
        <div class="form-horizontal">
            <div class="form-group">
                @*@Html.LabelFor(m => Model.Name, new { @class = "control-label col-sm-3" })*@
                @Html.Label("Name","Role Name", new { @class = "control-label col-sm-3" })
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control required" })
                    <div>
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Meh/Images/wait.gif" alt="wait" />
            Sending ...
        </span>

        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn btn-warning" data-dismiss="modal">Close</button>
    </div>

}